import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name:'farouk',
      email:'admin@admin.com',
      password:bcrypt.hashSync('1234', 8), 
      isAdmin: true,
    },
    {
      name:'mahdi',
      email:'mahdi@mahdi.com',
      password:bcrypt.hashSync('1234', 8), 
      isAdmin: false,
    }
  ],
    products:[
        {
            _id:'1',
            name: 'Nike sport T-shirt',
            category:'T-shirt',
            image:'/images/produit.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'adidas sport T-shirt',
            category:'T-shirt',
            image:'/images/produit.jpg',
            price: 150,
            countInStock: 20,
            brand: 'adidas',
            rating: "3.8",
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'lacoste sport T-shirt',
            category:'T-shirt',
            image:'/images/produit.jpg',
            price: 190,
            countInStock: 0,
            brand: 'lacoste',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Nike sport T-shirt',
            category:'T-shirt',
            image:'/images/produit.jpg',
            price: 100,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Nike sport T-shirt',
            category:'T-shirt',
            image:'/images/produit.jpg',
            price: 110,
            countInStock: 0,
            brand: 'Nike',
            rating: 4,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Nike sport T-shirt',
            category:'T-shirt',
            image:'/images/produit.jpg',
            price: 90,
            countInStock: 100,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};
export default data;